name: Release DevOps with Heroku

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP }} web
